// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../Joyinfood/foodItem.js', ['joyinfood.foodItem'], ['goog.dom.classes', 'goog.ui.Button', 'goog.ui.Control']);
goog.addDependency('../../../Joyinfood/friend.js', ['joyinfood.friend'], ['goog.dom.classes', 'goog.ui.Button', 'goog.ui.Control']);
goog.addDependency('../../../Joyinfood/joinAlert.js', ['joyinfood.joinAlert'], ['goog.dom.classes', 'goog.ui.Button', 'goog.ui.Control']);
goog.addDependency('../../../Joyinfood/labeledCheckbox.js', ['joyinfood.labeledCheckbox'], ['goog.dom.classes', 'goog.ui.Checkbox', 'goog.ui.Control']);
